apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stage-rolebinding
  namespace: staging
subjects:
- kind: User
  name: stage-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: stage-role
  apiGroup: rbac.authorization.k8s.io