# Default values for craftista
global:
  imageRegistry: docker.io
  imageTag: latest
  imagePullPolicy: Always

# Frontend Service
frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: hema995/craftista-frontend
    tag: ""
  service:
    type: LoadBalancer
    port: 3000
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi

# Catalogue Service
catalogue:
  enabled: true
  replicaCount: 1
  image:
    repository: hema995/craftista-catalogue
    tag: ""
  service:
    type: LoadBalancer
    port: 5000
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  mongodb:
    enabled: true
    persistence:
      size: 1Gi
      storageClass: standard

# Recommendation Service
recommendation:
  enabled: true
  replicaCount: 1
  image:
    repository: hema995/craftista-recommendation
    tag: ""
  service:
    type: LoadBalancer
    port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi

# Voting Service
voting:
  enabled: true
  replicaCount: 1
  image:
    repository: hema995/craftista-voting
    tag: ""
  service:
    type: LoadBalancer
    port: 8060
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  postgresql:
    enabled: true
    persistence:
      size: 1Gi
      storageClass: standard
    auth:
      username: voting-user-db
      password: votingpassword-db
      database: voting-postgres-db

# RBAC
rbac:
  create: true
  serviceAccountName: craftista-sa

# Environment-specific overrides
environment: dev